#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# If the user has not passed in a cookbook name use 'osx_bootstrap' for the cookbook
bootstrapCookbook=${1:-osx_bootstrap}

# If the user has not passed in a cookbook git source then use this cookbook
bootstrapCookbookGitSrc=${2:-https://github.com/rbowlby/osx_bootstrap}

# make userChefDir variable
userChefDir=~/chef

brewBin=/usr/local/bin/brew

clear

# introduction
cat <<EOF;
This script will:

1. Install the latest ChefDK package via Homebrew
2. Create a 'chef' directory in your user profile (home) directory
3. Download the 'osx_bootstrap' cookbook via Berkshelf
4. Run 'chef-client' to fully configure the workstation

EOF

# creating a Chef directory for Chef development
[[ ! -d "${userChefDir}" ]] && mkdir "${userChefDir}"

# create Berksfile so that we can install the correct cookbook dependencies
cat > "${userChefDir}/Berksfile" <<EOF;
source 'https://supermarket.chef.io'

cookbook '${bootstrapCookbook}', git: '${bootstrapCookbookGitSrc}'
EOF

# create client.rb file so that Chef client can find its dependant cookbooks
cat > "${userChefDir}/client.rb" <<EOF;
cookbook_path File.join(Dir.pwd, 'berks-cookbooks')
EOF

# install Homebrew
if [[ ! -e $brewBin ]]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install brew-cask
if ! $brewBin list brew-cask &>/dev/null; then
  brew install caskroom/cask/brew-cask
fi

# install chefDK
if ! $brewBin cask list chefdk &>/dev/null; then
  brew cask install chefdk
fi

# making sure that we are vendor cookbooks into a sub directory of the userChefDir
cd "${userChefDir}"
berks vendor

# run chef-client (installed by ChefDK) to bootstrap this machine
sudo -E chef-client -z -l error -c "${userChefDir}/client.rb" -o "$bootstrapCookbook"
